version: '3.8'
services:
  backend:
    build: .
    container_name: bb-backend
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - .:/core
    depends_on:
      - db
    command: python manage.py runserver 0.0.0.0:8000

  db:
    image: postgres:15
    container_name: budget-buddy-db
    environment:
      POSTGRES_DB: budget_buddy_db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data: