# Generated by Django 5.1 on 2025-05-20 04:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bankaccounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DebitTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('transaction_date', models.DateTimeField()),
                ('bank_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='debit_transactions', to='bankaccounts.bankaccount')),
            ],
        ),
    ]
