# Generated by Django 5.1 on 2025-05-21 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('debitTransaction', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='debittransaction',
            name='transaction_name',
            field=models.CharField(default='Debit Transaction', max_length=255),
        ),
    ]
