# Generated by Django 5.1 on 2025-05-21 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("debitTransaction", "0002_debittransaction_transaction_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="debittransaction",
            name="category",
            field=models.CharField(
                choices=[
                    ("Groceries", "Groceries"),
                    ("Rent", "Rent"),
                    ("Utilities", "Utilities"),
                    ("Entertainment", "Entertainment"),
                    ("Other", "Other"),
                ],
                default="Other",
                max_length=50,
            ),
        ),
    ]
