# Generated by Django 5.1 on 2025-05-20 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="BankAccount",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("bank_name", models.CharField(max_length=255)),
                ("account_name", models.CharField(max_length=255)),
                (
                    "balance",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
