# Generated by Django 5.1 on 2025-05-22 02:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("bankaccounts", "0003_bankaccount_account_number"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="bankaccount",
            name="interest_rate",
        ),
        migrations.RemoveField(
            model_name="bankaccount",
            name="maturity_date",
        ),
        migrations.RemoveField(
            model_name="bankaccount",
            name="withdrawal_limit",
        ),
        migrations.RemoveField(
            model_name="bankaccount",
            name="withdrawal_penalty",
        ),
    ]
