# Generated by Django 5.1 on 2025-05-23 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bankaccounts', '0004_remove_bankaccount_interest_rate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankaccount',
            name='is_over_limit',
            field=models.BooleanField(default=False),
        ),
    ]
