# Generated by Django 5.1 on 2025-05-20 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("bankaccounts", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("username", models.CharField(max_length=150, unique=True)),
                ("password", models.CharField(max_length=128)),
                ("date_joined", models.DateTimeField(auto_now_add=True)),
                (
                    "linked_bank_accounts",
                    models.ManyToManyField(
                        blank=True, related_name="users", to="bankaccounts.bankaccount"
                    ),
                ),
            ],
        ),
    ]
