# Generated by Django 5.1 on 2025-05-21 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("creditTransaction", "0003_alter_credittransaction_bank_account"),
    ]

    operations = [
        migrations.AddField(
            model_name="credittransaction",
            name="category",
            field=models.CharField(
                choices=[
                    ("Salary", "Salary"),
                    ("Bonus", "Bonus"),
                    ("Refund", "Refund"),
                    ("Other", "Other"),
                ],
                default="Other",
                max_length=50,
            ),
        ),
    ]
