# Generated by Django 5.1 on 2025-05-23 02:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bankAccount", "0004_remove_bankaccount_interest_rate_and_more"),
        ("financialGoals", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="financialgoal",
            name="bank_account",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="financial_goals",
                to="bankAccount.bankaccount",
            ),
        ),
    ]
