# Generated by Django 5.1 on 2025-05-26 19:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("financialGoals", "0004_alter_financialgoal_user"),
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="financialgoal",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="financial_goals",
                to="user.user",
            ),
        ),
    ]
